// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: video_cut.proto

package videocut

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoCutTaskData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideocutSize  int32           `protobuf:"varint,4,opt,name=VideocutSize,proto3" json:"VideocutSize,omitempty"`
	VideocutItems []*VideoCutItem `protobuf:"bytes,5,rep,name=VideocutItems,proto3" json:"VideocutItems,omitempty"`
}

func (x *VideoCutTaskData) Reset() {
	*x = VideoCutTaskData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_cut_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoCutTaskData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCutTaskData) ProtoMessage() {}

func (x *VideoCutTaskData) ProtoReflect() protoreflect.Message {
	mi := &file_video_cut_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCutTaskData.ProtoReflect.Descriptor instead.
func (*VideoCutTaskData) Descriptor() ([]byte, []int) {
	return file_video_cut_proto_rawDescGZIP(), []int{0}
}

func (x *VideoCutTaskData) GetVideocutSize() int32 {
	if x != nil {
		return x.VideocutSize
	}
	return 0
}

func (x *VideoCutTaskData) GetVideocutItems() []*VideoCutItem {
	if x != nil {
		return x.VideocutItems
	}
	return nil
}

type VideoCutItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideocutType string  `protobuf:"bytes,1,opt,name=VideocutType,proto3" json:"VideocutType,omitempty"` // 切片类型
	HeadIndex    int32   `protobuf:"varint,2,opt,name=HeadIndex,proto3" json:"HeadIndex,omitempty"`      // 镜头起始帧
	TailIndex    int32   `protobuf:"varint,3,opt,name=TailIndex,proto3" json:"TailIndex,omitempty"`      // 镜头终止帧
	StartTime    float32 `protobuf:"fixed32,4,opt,name=StartTime,proto3" json:"StartTime,omitempty"`     // 镜头起始时间
	EndTime      float32 `protobuf:"fixed32,5,opt,name=EndTime,proto3" json:"EndTime,omitempty"`         // 镜头终止时间
}

func (x *VideoCutItem) Reset() {
	*x = VideoCutItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_cut_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoCutItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCutItem) ProtoMessage() {}

func (x *VideoCutItem) ProtoReflect() protoreflect.Message {
	mi := &file_video_cut_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCutItem.ProtoReflect.Descriptor instead.
func (*VideoCutItem) Descriptor() ([]byte, []int) {
	return file_video_cut_proto_rawDescGZIP(), []int{1}
}

func (x *VideoCutItem) GetVideocutType() string {
	if x != nil {
		return x.VideocutType
	}
	return ""
}

func (x *VideoCutItem) GetHeadIndex() int32 {
	if x != nil {
		return x.HeadIndex
	}
	return 0
}

func (x *VideoCutItem) GetTailIndex() int32 {
	if x != nil {
		return x.TailIndex
	}
	return 0
}

func (x *VideoCutItem) GetStartTime() float32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *VideoCutItem) GetEndTime() float32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

var File_video_cut_proto protoreflect.FileDescriptor

var file_video_cut_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x63, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x13, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x63, 0x75, 0x74, 0x22, 0x7f, 0x0a, 0x10, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43,
	0x75, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x63, 0x75, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x63, 0x75, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x47,
	0x0a, 0x0d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x63, 0x75, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x63, 0x75, 0x74, 0x2e, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x43, 0x75, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x63,
	0x75, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xa6, 0x01, 0x0a, 0x0c, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x43, 0x75, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x22, 0x0a, 0x0c, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x63, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x63, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x48, 0x65, 0x61, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x48, 0x65, 0x61, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x61,
	0x69, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x54,
	0x61, 0x69, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x42, 0x58, 0x5a, 0x56, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54,
	0x65, 0x6e, 0x63, 0x65, 0x6e, 0x74, 0x2d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2d, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x2d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2d, 0x73, 0x64, 0x6b,
	0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x73, 0x70, 0x65,
	0x63, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x63, 0x75, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_video_cut_proto_rawDescOnce sync.Once
	file_video_cut_proto_rawDescData = file_video_cut_proto_rawDesc
)

func file_video_cut_proto_rawDescGZIP() []byte {
	file_video_cut_proto_rawDescOnce.Do(func() {
		file_video_cut_proto_rawDescData = protoimpl.X.CompressGZIP(file_video_cut_proto_rawDescData)
	})
	return file_video_cut_proto_rawDescData
}

var file_video_cut_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_video_cut_proto_goTypes = []interface{}{
	(*VideoCutTaskData)(nil), // 0: trpc.media.videocut.VideoCutTaskData
	(*VideoCutItem)(nil),     // 1: trpc.media.videocut.VideoCutItem
}
var file_video_cut_proto_depIdxs = []int32{
	1, // 0: trpc.media.videocut.VideoCutTaskData.VideocutItems:type_name -> trpc.media.videocut.VideoCutItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_video_cut_proto_init() }
func file_video_cut_proto_init() {
	if File_video_cut_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_video_cut_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoCutTaskData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_cut_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoCutItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_video_cut_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_video_cut_proto_goTypes,
		DependencyIndexes: file_video_cut_proto_depIdxs,
		MessageInfos:      file_video_cut_proto_msgTypes,
	}.Build()
	File_video_cut_proto = out.File
	file_video_cut_proto_rawDesc = nil
	file_video_cut_proto_goTypes = nil
	file_video_cut_proto_depIdxs = nil
}
