// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: toolkit.proto

package toolkit

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/Tencent-media-asset-system-sdk/media-platform-sdk-go/protobuf-spec/apicommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToolProviderType int32

const (
	ToolProviderType_TOOL_PROVIDER_UNKNOWN ToolProviderType = 0 // 未知提供者
	ToolProviderType_TOOL_PROVIDER_AIMEDIA ToolProviderType = 1 // 媒体中台工具
	ToolProviderType_TOOL_PROVIDER_PCG     ToolProviderType = 2 // PCG工具
)

// Enum value maps for ToolProviderType.
var (
	ToolProviderType_name = map[int32]string{
		0: "TOOL_PROVIDER_UNKNOWN",
		1: "TOOL_PROVIDER_AIMEDIA",
		2: "TOOL_PROVIDER_PCG",
	}
	ToolProviderType_value = map[string]int32{
		"TOOL_PROVIDER_UNKNOWN": 0,
		"TOOL_PROVIDER_AIMEDIA": 1,
		"TOOL_PROVIDER_PCG":     2,
	}
)

func (x ToolProviderType) Enum() *ToolProviderType {
	p := new(ToolProviderType)
	*p = x
	return p
}

func (x ToolProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_toolkit_proto_enumTypes[0].Descriptor()
}

func (ToolProviderType) Type() protoreflect.EnumType {
	return &file_toolkit_proto_enumTypes[0]
}

func (x ToolProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolProviderType.Descriptor instead.
func (ToolProviderType) EnumDescriptor() ([]byte, []int) {
	return file_toolkit_proto_rawDescGZIP(), []int{0}
}

type ToolCategoryType int32

const (
	ToolCategoryType_TOOL_CATEGORY_UNKNOWN             ToolCategoryType = 0 // 未知分类
	ToolCategoryType_TOOL_CATEGORY_VIDEO_QUALITY       ToolCategoryType = 1 // 视频画质工具
	ToolCategoryType_TOOL_CATEGORY_VIDEO_UNDERSTANDING ToolCategoryType = 2 // 视频理解工具
)

// Enum value maps for ToolCategoryType.
var (
	ToolCategoryType_name = map[int32]string{
		0: "TOOL_CATEGORY_UNKNOWN",
		1: "TOOL_CATEGORY_VIDEO_QUALITY",
		2: "TOOL_CATEGORY_VIDEO_UNDERSTANDING",
	}
	ToolCategoryType_value = map[string]int32{
		"TOOL_CATEGORY_UNKNOWN":             0,
		"TOOL_CATEGORY_VIDEO_QUALITY":       1,
		"TOOL_CATEGORY_VIDEO_UNDERSTANDING": 2,
	}
)

func (x ToolCategoryType) Enum() *ToolCategoryType {
	p := new(ToolCategoryType)
	*p = x
	return p
}

func (x ToolCategoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolCategoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_toolkit_proto_enumTypes[1].Descriptor()
}

func (ToolCategoryType) Type() protoreflect.EnumType {
	return &file_toolkit_proto_enumTypes[1]
}

func (x ToolCategoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolCategoryType.Descriptor instead.
func (ToolCategoryType) EnumDescriptor() ([]byte, []int) {
	return file_toolkit_proto_rawDescGZIP(), []int{1}
}

type ToolAccessType int32

const (
	ToolAccessType_TOOL_ACCESS_UNKNOWN  ToolAccessType = 0 // 未知访问
	ToolAccessType_TOOL_ACCESS_INTERNAL ToolAccessType = 1 // 内部访问
	ToolAccessType_TOOL_ACCESS_EXTERNAL ToolAccessType = 2 // 外部访问
)

// Enum value maps for ToolAccessType.
var (
	ToolAccessType_name = map[int32]string{
		0: "TOOL_ACCESS_UNKNOWN",
		1: "TOOL_ACCESS_INTERNAL",
		2: "TOOL_ACCESS_EXTERNAL",
	}
	ToolAccessType_value = map[string]int32{
		"TOOL_ACCESS_UNKNOWN":  0,
		"TOOL_ACCESS_INTERNAL": 1,
		"TOOL_ACCESS_EXTERNAL": 2,
	}
)

func (x ToolAccessType) Enum() *ToolAccessType {
	p := new(ToolAccessType)
	*p = x
	return p
}

func (x ToolAccessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolAccessType) Descriptor() protoreflect.EnumDescriptor {
	return file_toolkit_proto_enumTypes[2].Descriptor()
}

func (ToolAccessType) Type() protoreflect.EnumType {
	return &file_toolkit_proto_enumTypes[2]
}

func (x ToolAccessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolAccessType.Descriptor instead.
func (ToolAccessType) EnumDescriptor() ([]byte, []int) {
	return file_toolkit_proto_rawDescGZIP(), []int{2}
}

type ToolInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToolID          string `protobuf:"bytes,1,opt,name=ToolID,proto3" json:"ToolID,omitempty"`
	ToolName        string `protobuf:"bytes,2,opt,name=ToolName,proto3" json:"ToolName,omitempty"`
	ToolDescription string `protobuf:"bytes,3,opt,name=ToolDescription,proto3" json:"ToolDescription,omitempty"`
	ToolIconURI     string `protobuf:"bytes,4,opt,name=ToolIconURI,proto3" json:"ToolIconURI,omitempty"`
	ToolEntryURI    string `protobuf:"bytes,5,opt,name=ToolEntryURI,proto3" json:"ToolEntryURI,omitempty"`
	//ToolCategoryType ToolCategory = 6;
	//ToolProviderType ToolProvider = 7;
	ToolAccess ToolAccessType `protobuf:"varint,8,opt,name=ToolAccess,proto3,enum=trpc.media.toolkit.ToolAccessType" json:"ToolAccess,omitempty"`
	ToolOrder  int32          `protobuf:"varint,9,opt,name=ToolOrder,proto3" json:"ToolOrder,omitempty"`
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toolkit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_toolkit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_toolkit_proto_rawDescGZIP(), []int{0}
}

func (x *ToolInfo) GetToolID() string {
	if x != nil {
		return x.ToolID
	}
	return ""
}

func (x *ToolInfo) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolInfo) GetToolDescription() string {
	if x != nil {
		return x.ToolDescription
	}
	return ""
}

func (x *ToolInfo) GetToolIconURI() string {
	if x != nil {
		return x.ToolIconURI
	}
	return ""
}

func (x *ToolInfo) GetToolEntryURI() string {
	if x != nil {
		return x.ToolEntryURI
	}
	return ""
}

func (x *ToolInfo) GetToolAccess() ToolAccessType {
	if x != nil {
		return x.ToolAccess
	}
	return ToolAccessType_TOOL_ACCESS_UNKNOWN
}

func (x *ToolInfo) GetToolOrder() int32 {
	if x != nil {
		return x.ToolOrder
	}
	return 0
}

type DescribeToolkitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DescribeToolkitsRequest) Reset() {
	*x = DescribeToolkitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toolkit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeToolkitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeToolkitsRequest) ProtoMessage() {}

func (x *DescribeToolkitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_toolkit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeToolkitsRequest.ProtoReflect.Descriptor instead.
func (*DescribeToolkitsRequest) Descriptor() ([]byte, []int) {
	return file_toolkit_proto_rawDescGZIP(), []int{1}
}

type DescribeToolkitsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToolSet []*ToolInfo `protobuf:"bytes,1,rep,name=ToolSet,proto3" json:"ToolSet,omitempty"` //uint32 TotalCount = 2;
}

func (x *DescribeToolkitsResponse) Reset() {
	*x = DescribeToolkitsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toolkit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeToolkitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeToolkitsResponse) ProtoMessage() {}

func (x *DescribeToolkitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_toolkit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeToolkitsResponse.ProtoReflect.Descriptor instead.
func (*DescribeToolkitsResponse) Descriptor() ([]byte, []int) {
	return file_toolkit_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeToolkitsResponse) GetToolSet() []*ToolInfo {
	if x != nil {
		return x.ToolSet
	}
	return nil
}

type ToolkitDefaultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ToolkitDefaultRequest) Reset() {
	*x = ToolkitDefaultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toolkit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToolkitDefaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolkitDefaultRequest) ProtoMessage() {}

func (x *ToolkitDefaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_toolkit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolkitDefaultRequest.ProtoReflect.Descriptor instead.
func (*ToolkitDefaultRequest) Descriptor() ([]byte, []int) {
	return file_toolkit_proto_rawDescGZIP(), []int{3}
}

type ToolkitDefaultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ToolkitDefaultResponse) Reset() {
	*x = ToolkitDefaultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toolkit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToolkitDefaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolkitDefaultResponse) ProtoMessage() {}

func (x *ToolkitDefaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_toolkit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolkitDefaultResponse.ProtoReflect.Descriptor instead.
func (*ToolkitDefaultResponse) Descriptor() ([]byte, []int) {
	return file_toolkit_proto_rawDescGZIP(), []int{4}
}

var File_toolkit_proto protoreflect.FileDescriptor

var file_toolkit_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x74, 0x6f, 0x6f, 0x6c,
	0x6b, 0x69, 0x74, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x90, 0x02, 0x0a, 0x08, 0x54, 0x6f, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x54, 0x6f, 0x6f, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x54, 0x6f, 0x6f, 0x6c, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x6f, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x6f, 0x6f, 0x6c, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x54, 0x6f, 0x6f, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x54, 0x6f, 0x6f,
	0x6c, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b,
	0x54, 0x6f, 0x6f, 0x6c, 0x49, 0x63, 0x6f, 0x6e, 0x55, 0x52, 0x49, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x54, 0x6f, 0x6f, 0x6c, 0x49, 0x63, 0x6f, 0x6e, 0x55, 0x52, 0x49, 0x12, 0x22,
	0x0a, 0x0c, 0x54, 0x6f, 0x6f, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x55, 0x52, 0x49, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x54, 0x6f, 0x6f, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x55,
	0x52, 0x49, 0x12, 0x42, 0x0a, 0x0a, 0x54, 0x6f, 0x6f, 0x6c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x2e, 0x54, 0x6f, 0x6f, 0x6c,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x54, 0x6f, 0x6f, 0x6c,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x6f, 0x6c, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x54, 0x6f, 0x6f, 0x6c, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x54, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x52, 0x0a, 0x18, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x6b,
	0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x54,
	0x6f, 0x6f, 0x6c, 0x53, 0x65, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x74,
	0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69,
	0x74, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x54, 0x6f, 0x6f, 0x6c,
	0x53, 0x65, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x54, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16,
	0x54, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x5f, 0x0a, 0x10, 0x54, 0x6f, 0x6f, 0x6c, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x4f,
	0x4f, 0x4c, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x4f, 0x4f, 0x4c, 0x5f, 0x50, 0x52,
	0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x41, 0x49, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x10, 0x01,
	0x12, 0x15, 0x0a, 0x11, 0x54, 0x4f, 0x4f, 0x4c, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45,
	0x52, 0x5f, 0x50, 0x43, 0x47, 0x10, 0x02, 0x2a, 0x75, 0x0a, 0x10, 0x54, 0x6f, 0x6f, 0x6c, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x54,
	0x4f, 0x4f, 0x4c, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x54, 0x4f, 0x4f, 0x4c, 0x5f, 0x43,
	0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x5f, 0x51, 0x55,
	0x41, 0x4c, 0x49, 0x54, 0x59, 0x10, 0x01, 0x12, 0x25, 0x0a, 0x21, 0x54, 0x4f, 0x4f, 0x4c, 0x5f,
	0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x5f, 0x55,
	0x4e, 0x44, 0x45, 0x52, 0x53, 0x54, 0x41, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x2a, 0x5d,
	0x0a, 0x0e, 0x54, 0x6f, 0x6f, 0x6c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x17, 0x0a, 0x13, 0x54, 0x4f, 0x4f, 0x4c, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x54, 0x4f, 0x4f,
	0x4c, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41,
	0x4c, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x54, 0x4f, 0x4f, 0x4c, 0x5f, 0x41, 0x43, 0x43, 0x45,
	0x53, 0x53, 0x5f, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x02, 0x32, 0x78, 0x0a,
	0x07, 0x54, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x12, 0x6d, 0x0a, 0x10, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x73, 0x12, 0x2b, 0x2e, 0x74,
	0x72, 0x70, 0x63, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69,
	0x74, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x6b, 0x69,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x74, 0x72, 0x70, 0x63,
	0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x2e, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x57, 0x5a, 0x55, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x65, 0x6e, 0x63, 0x65, 0x6e, 0x74, 0x2d, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x2d, 0x61, 0x73, 0x73, 0x65, 0x74, 0x2d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_toolkit_proto_rawDescOnce sync.Once
	file_toolkit_proto_rawDescData = file_toolkit_proto_rawDesc
)

func file_toolkit_proto_rawDescGZIP() []byte {
	file_toolkit_proto_rawDescOnce.Do(func() {
		file_toolkit_proto_rawDescData = protoimpl.X.CompressGZIP(file_toolkit_proto_rawDescData)
	})
	return file_toolkit_proto_rawDescData
}

var file_toolkit_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_toolkit_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_toolkit_proto_goTypes = []interface{}{
	(ToolProviderType)(0),            // 0: trpc.media.toolkit.ToolProviderType
	(ToolCategoryType)(0),            // 1: trpc.media.toolkit.ToolCategoryType
	(ToolAccessType)(0),              // 2: trpc.media.toolkit.ToolAccessType
	(*ToolInfo)(nil),                 // 3: trpc.media.toolkit.ToolInfo
	(*DescribeToolkitsRequest)(nil),  // 4: trpc.media.toolkit.DescribeToolkitsRequest
	(*DescribeToolkitsResponse)(nil), // 5: trpc.media.toolkit.DescribeToolkitsResponse
	(*ToolkitDefaultRequest)(nil),    // 6: trpc.media.toolkit.ToolkitDefaultRequest
	(*ToolkitDefaultResponse)(nil),   // 7: trpc.media.toolkit.ToolkitDefaultResponse
}
var file_toolkit_proto_depIdxs = []int32{
	2, // 0: trpc.media.toolkit.ToolInfo.ToolAccess:type_name -> trpc.media.toolkit.ToolAccessType
	3, // 1: trpc.media.toolkit.DescribeToolkitsResponse.ToolSet:type_name -> trpc.media.toolkit.ToolInfo
	4, // 2: trpc.media.toolkit.Toolkit.DescribeToolkits:input_type -> trpc.media.toolkit.DescribeToolkitsRequest
	5, // 3: trpc.media.toolkit.Toolkit.DescribeToolkits:output_type -> trpc.media.toolkit.DescribeToolkitsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_toolkit_proto_init() }
func file_toolkit_proto_init() {
	if File_toolkit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_toolkit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToolInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toolkit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeToolkitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toolkit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeToolkitsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toolkit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToolkitDefaultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toolkit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToolkitDefaultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_toolkit_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_toolkit_proto_goTypes,
		DependencyIndexes: file_toolkit_proto_depIdxs,
		EnumInfos:         file_toolkit_proto_enumTypes,
		MessageInfos:      file_toolkit_proto_msgTypes,
	}.Build()
	File_toolkit_proto = out.File
	file_toolkit_proto_rawDesc = nil
	file_toolkit_proto_goTypes = nil
	file_toolkit_proto_depIdxs = nil
}
